import pandas as pd
from sqlalchemy import NVARCHAR, Integer


def importa_atf(gc, engine):
    # ATF
    ws_atf = gc.open_by_key('1N6k7Lqk4jctrk-nhovjsuZVgaPtSI7LNWScwpR0xxWc').sheet1

    data = pd.DataFrame(ws_atf.get_all_records())
    data.columns = ['Marca temporal', 'Usuario Evaluador', 'Perfil Evaluador', 'SN - Cod',
                    'Usuario Asesor', 'Teléfono Cliente', 'Nombre Cliente', 'TMO',
                    'SOT - Caso', 'Motivo', 'Detalle llamada',
                    '1.1 Excede el tiempo de espera permitido',
                    '1.2 Personaliza',
                    '1.3 Asesor tutea al cliente',
                    '1.4 Cumplimiento de speech bienvenida - despedida',
                    '1.5 Utiliza un lenguaje inapropiado con el UF',
                    '1.6 Atiende la llamada en el tiempo establecido',
                    '1.7 Solicita tiempos de espera innecesarios',
                    '1.8 Indica el motivo del uso del tiempo de espera',
                    '1.9 Retoma agradeciendo la espera',
                    '2.1 Presta atencion a comentarios_solicitudes de UF',
                    '2.2 Silencios incomodos',
                    '2.3 Solicita_confirma mas de una vez una informacion innecesariamente',
                    '2.4 Identifica de forma completa el motivo de la incidencia_caso',
                    '2.5 Identifica el numero del cual llama',
                    '3.1 Suministra informacion incompleta',
                    '3.2 Suministra informacion incorrecta',
                    '3.3 Derivacion correcta casos',
                    '3.4 Descartes para entrega de solucion',
                    '3.5 Gestiona reagendamiento',
                    '3.6 Cambia estado de caso',
                    '3.7 Trabaja variacion_incidencias',
                    '3.8 Solicitud y validacion de los datos',
                    '3.9 Sondeo correcto y completo',
                    '3.10 Utilizacion de aplicaciones',
                    '4.1 Utiliza plantilla correcta para el registro',
                    '4.2 Tipifica de manera correcta_completa en aplicativos',
                    '5.1 Manejo de clientes criticos',
                    '5.2 Interrumpe al cliente',
                    '5.3 Lenguaje adecuado y entonacion de la voz',
                    '5.4 Demuestra mala actitud',
                    '5.5 Exceso de confianza con el UF',
                    '6.1 Recomienda smart home',
                    'Mala Praxis', 'Observaciones', 'Fecha llamada']

    data.to_sql('ATF', con=engine,
                if_exists='replace',
                dtype={'Marca temporal': NVARCHAR(length=100),
                       'Usuario Evaluador': NVARCHAR(length=100),
                       'Perfil Evaluador': NVARCHAR(length=50),
                       'SN - Cod': NVARCHAR(length=20),
                       'Usuario Asesor': NVARCHAR(length=100),
                       'Teléfono Cliente': NVARCHAR(length=20),
                       'Nombre Cliente': NVARCHAR(length=100),
                       'TMO': Integer(),
                       'SOT - Caso': NVARCHAR(length=20),
                       'Motivo': NVARCHAR(length=200),
                       'Detalle llamada': NVARCHAR(length=3500),
                       '1.1 Excede el tiempo de espera permitido': NVARCHAR(length=4),
                       '1.2 Personaliza': NVARCHAR(length=4),
                       '1.3 Asesor tutea al cliente': NVARCHAR(length=4),
                       '1.4 Cumplimiento de speech bienvenida - despedida': NVARCHAR(length=4),
                       '1.5 Utiliza un lenguaje inapropiado con el UF': NVARCHAR(length=4),
                       '1.6 Atiende la llamada en el tiempo establecido': NVARCHAR(length=4),
                       '1.7 Solicita tiempos de espera innecesarios': NVARCHAR(length=4),
                       '1.8 Indica el motivo del uso del tiempo de espera': NVARCHAR(length=4),
                       '1.9 Retoma agradeciendo la espera': NVARCHAR(length=4),
                       '2.1 Presta atencion a comentarios_solicitudes de UF': NVARCHAR(length=4),
                       '2.2 Silencios incomodos': NVARCHAR(length=4),
                       '2.3 Solicita_confirma mas de una vez una informacion innecesariamente': NVARCHAR(length=4),
                       '2.4 Identifica de forma completa el motivo de la incidencia_caso': NVARCHAR(length=4),
                       '2.5 Identifica el numero del cual llama': NVARCHAR(length=4),
                       '3.1 Suministra informacion incompleta': NVARCHAR(length=4),
                       '3.2 Suministra informacion incorrecta': NVARCHAR(length=4),
                       '3.3 Derivacion correcta casos': NVARCHAR(length=4),
                       '3.4 Descartes para entrega de solucion': NVARCHAR(length=4),
                       '3.5 Gestiona reagendamiento': NVARCHAR(length=4),
                       '3.6 Cambia estado de caso': NVARCHAR(length=4),
                       '3.7 Trabaja variacion_incidencias': NVARCHAR(length=4),
                       '3.8 Solicitud y validacion de los datos': NVARCHAR(length=4),
                       '3.9 Sondeo correcto y completo': NVARCHAR(length=4),
                       '3.10 Utilizacion de aplicaciones': NVARCHAR(length=4),
                       '4.1 Utiliza plantilla correcta para el registro': NVARCHAR(length=4),
                       '4.2 Tipifica de manera correcta_completa en aplicativos': NVARCHAR(length=4),
                       '5.1 Manejo de clientes criticos': NVARCHAR(length=4),
                       '5.2 Interrumpe al cliente': NVARCHAR(length=4),
                       '5.3 Lenguaje adecuado y entonacion de la voz': NVARCHAR(length=4),
                       '5.4 Demuestra mala actitud': NVARCHAR(length=4),
                       '5.5 Exceso de confianza con el UF': NVARCHAR(length=4),
                       '6.1 Recomienda smart home': NVARCHAR(length=4),
                       'Mala Praxis': NVARCHAR(length=200),
                       'Observaciones': NVARCHAR(length=3500),
                       'Fecha llamada': NVARCHAR(length=100)})